spring:
  datasource:
    url: jdbc:mariadb://${UMUL_DB_HOST}:${UMUL_DB_PORT}/${UMUL_DATABASE_NAME}?useSSL=false
    username: ${UMUL_DB_USER_NAME}
    password: ${UMUL_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect

server:
  netty:
    connection-timeout: 1800000